config/routes.rb
Rails.application.routes.draw do

  root 'build_info#index'

  resources :build_info
  resources :unit
  resources :user

  get 'signup' => 'user#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get    "upvote/:id"   => 'build_info#upvote'
  get    "downvote/:id"   => 'build_info#downvote'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token

  has_many :build_infos

  before_save { self.user_email = user_email.downcase }
  validates_presence_of :user_name
  validates_uniqueness_of :user_name, :case_sensitive => false
  validates_uniqueness_of :user_email
  validates :password, length: {minimum: 8}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :user_email, presence: true, length: {maximum: 255}, format: {with: VALID_EMAIL_REGEX}
  has_secure_password

  def to_param
    user_name.downcase
  end

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def show
    @user = User.find_by_user_name(params[:id])
  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'Welcome to builder!'
      redirect_to root_url
    else
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:user_name, :user_email, :password, :password_confirmation)
  end

end

app/views/user/index.html.erb
<br>
<% @users.each do |user| %>
    Username: <%= user.user_name %> <br>
    Email: <%= user.user_email %> <br>
    Password: <%= user.password_digest %> <br><br>
<% end %>

app/views/user/new.html.erb
<% if logged_in? %>
    <script type="text/javascript">
        window.location.href = "/"
    </script>
<% end %>
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<% if @user.errors.any? %>
    <div id="error_explanation">
      <div class="alert bg-danger">
        The form contains <%= pluralize(@user.errors.count, 'error') %>.
      </div>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li class="text-danger"><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for :user, :url => {:action => 'create'} do |f| %>
        <div class="form-group">
          <%= f.label :username %>
          <%= f.text_field :user_name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :user_email, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :confirmation, 'Confirmation' %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
        <%= f.submit 'Create my account', class: 'btn btn-primary form-control' %>
    <% end %>
  </div>
</div>

app/views/user/show.html.erb
<p>
<h2><%= @user.user_name %></h2>
<strong>Builds Created:</strong>
<ul>
<% @user.build_infos.each do |build| %>
    <li>
      <img class="fixed-icon" title="<%= build.race.race_name %>" src="<%= asset_path build.race.race_image %>"/>
      v
      <img class="fixed-icon" title="<%= build.versus_race.race_name %>" src="<%= asset_path build.versus_race.race_image %>"/>
      <%= link_to build.name, build_info_path(build) %>

      <span class="glyphicon glyphicon-triangle-right"></span>

      <%= pluralize(build.rating, 'point') %>
      <small> <%= build.rating > 0 ? (build.upvotes/(build.upvotes+build.downvotes)*100) : 0 %>
        %
      </small>
    </li>
<% end %>
</ul>
</p>