config/routes.rb
Rails.application.routes.draw do

  root 'build_info#index'

  resources :build_info
  resources :unit
  resources :user

  get 'signup' => 'user#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get    "upvote/:id"   => 'build_info#upvote'
  get    "downvote/:id"   => 'build_info#downvote'

end

app/models/build_info.rb
class BuildInfo < ActiveRecord::Base

  attr_accessor :user_vote
  attr_accessor :build_steps
  attr_accessor :build_guide

  belongs_to :build_type
  belongs_to :race
  belongs_to :versus_race, :foreign_key => 'versus_race_id', :class_name => "Race"
  belongs_to :difficulty
  belongs_to :expansion
  belongs_to :user

  has_many :key_units
  has_many :units, :through => :key_units

  def to_param
    "#{id}-#{slug}"
  end

  def slug
    name.downcase.gsub(' ', '-')
  end

  def rating
    upvotes-downvotes
  end

  def update_votes?
    requires_update(self)
  end

  def update_voting
    update_votes(self)
  end

end

app/controllers/build_info_controller.rb
class BuildInfoController < ApplicationController

  # Show a build based on the id passed to the url
  def show
    @build_info = find
    attach_steps @build_info
    attach_guide @build_info
  end

  # Find a build based on the id passed to the url
  # if user is logged in checks what their vote was
  # on this build and attaches it to the object
  def find
    @build_info = BuildInfo.find(params[:id])
    if (!@build_info.nil? && requires_update?(@build_info))
      update_votes(@build_info)
    end
    if logged_in?
      @build_info.user_vote = Vote.where('build_info_id = ? AND user_id = ?', @build_info.id, current_user.id).first
    end
    @build_info
  end

  # Get all builds
  def index
    @build_infos = BuildInfo.all
  end

  # Upvote the build for the id passed to the url
  def upvote
    # ensure user logged in
    if logged_in?
      @build_info = find
      # If current vote is upvote then clear
      if (!@build_info.user_vote.nil? && @build_info.user_vote.upvote)
        @build_info.user_vote.upvote = false
        # Else true upvote and false downvote
      else
        @build_info.user_vote = Vote.new if @build_info.user_vote.nil?
        @build_info.user_vote.user_id = current_user.id
        @build_info.user_vote.build_info_id = @build_info.id
        @build_info.user_vote.upvote = true
        @build_info.user_vote.downvote = false
      end
      @build_info.user_vote.save
      redirect_to build_info_path @build_info
    else
      redirect_to signup_url
    end
  end

  # Downvote the build for the id passed to the url
  def downvote
    # ensure user logged in
    if logged_in?
      @build_info = find
      # If current vote is downvote then clear
      if (!@build_info.user_vote.nil? && @build_info.user_vote.downvote)
        @build_info.user_vote.downvote = false
        # Else true downvote and false upvote
      else
        @build_info.user_vote = Vote.new if @build_info.user_vote.nil?
        @build_info.user_vote.user_id = current_user.id
        @build_info.user_vote.build_info_id = @build_info.id
        @build_info.user_vote.upvote = false
        @build_info.user_vote.downvote = true
      end
      @build_info.user_vote.save
      redirect_to build_info_path @build_info
    else
      redirect_to signup_url
    end
  end

  private
  # Require update if never updated or updated longer than 5 minutes ago
  def requires_update?(build_info)
    (build_info.updated.nil? or build_info.updated < 5.minutes.ago)
  end

  # Search for votes relating to a build_info
  # Set them in the object and SAVE
  def update_votes(build_info)
    upvotes = 0
    downvotes = 0
    Vote.where(:build_info_id => build_info.id.to_i).all.each do |vote|
      upvotes += 1 if vote.upvote
      downvotes += 1 if vote.downvote
    end
    build_info.update(upvotes: upvotes)
    build_info.update(downvotes: downvotes)
    build_info.update(updated: Time.now)
    build_info.save
  end

  def attach_steps(build_info)
    build_info.build_steps = Step.where('build_info_id = ?', build_info.id).order('ordering')
    build_info
  end

  def attach_guide(build_info)
    build_info.build_guide = Guide.where('build_info_id = ?', build_info.id).first
    build_info
  end

end

app/views/build_info/index.html.erb
<% if !logged_in? %>
    <div class="jumbotron">
      <span title="Hide" class="glyphicon glyphicon-collapse-up hide-jumbotron"></span>

      <div class="container">


        <h1>Welcome to builder</h1>

        <p>Builder is a Starcraft builds community. Sign Up to submit new builds or to vote on existing builds.</p>

        <p><a class="btn btn-primary btn-lg" href="<%= signup_path %>" role="button">Sign Up &raquo;</a></p>
      </div>
    </div>
<% end %>
<table class="table table-hover" id="build-info-table">
  <thead>
  <th>Race</th>
  <th>Type</th>
  <th>Versus</th>
  <th>Name</th>
  <th>Rating</th>
  <th>Key Units</th>
  <th>Expansion</th>
  <th>Difficulty</th>
  <th>Created</th>
  <th>Creator</th>
  </thead>
  <tbody>
  <% @build_infos.each do |build| %>
      <tr>
        <td>
          <a href="<%= build.to_param %>">
            <img title="<%= build.race.race_name %>" src="<%= asset_path build.race.race_image %>"/>
            <span class="hidden">race:<%= build.race.race_name %></span>
          </a>
        </td>
        <td>
          <a href="<%= build_info_path(build) %>">
            <%= build.build_type.type_name %>
          </a>
        </td>
        <td>
          <a href="<%= build_info_path(build) %>">
            <img title="<%= build.versus_race.race_name %>" src="<%= asset_path build.versus_race.race_image %>"/>
            <span class="hidden">versus:<%= build.versus_race.race_name %></span>
          </a>
        </td>
        <td>
          <a href="<%= build_info_path(build) %>">
            <%= build.name %>
          </a>
        </td>
        <td>
          <a href="<%= build_info_path(build) %>">
            <%= build.rating %>
          </a>
        </td>
        <td>
          <a href="<%= build_info_path(build) %>">
            <% build.units.each do |unit| %>
                <img title="<%= unit.unit_name %>" src="<%= asset_path unit.unit_image %>"/>
                <span class="hidden"><%= unit.unit_name %></span>
            <% end %>
          </a>
        </td>
        <td>
          <a href="<%= build_info_path(build) %>">
            <img title="<%= build.expansion.expansion_name %>" src="<%= asset_path build.expansion.expansion_image %>"/>
            <span class="hidden"><%= build.expansion.expansion_name %></span>
          </a>
        </td>
        <td><a href="<%= build_info_path(build) %>"><%= build.difficulty.difficulty_name %></a></td>
        <td><a href="<%= build_info_path(build) %>"><%= build.created.strftime('%d/%m/%Y %I:%M%p') %></a></td>
        <td><a href="<%= build_info_path(build) %>"><%= build.user.user_name %></a></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/build_info/show.html.erb
<%
   # workout the users current votes
   if !@build_info.user_vote.nil?
     upvote = @build_info.user_vote.upvote
     downvote = @build_info.user_vote.downvote
   end
%>
<h2><%= @build_info.name %>
  <small class="noselect" title="Votes are calculated every 5 minutes">
    <% if logged_in? %>
        <a href="../upvote/<%= @build_info.to_param %>" class="glyphicon glyphicon-arrow-up vote <%= 'selected-vote' if upvote %>"></a>
        <a href="../downvote/<%= @build_info.to_param %>" class="glyphicon glyphicon-arrow-down vote <%= 'selected-vote' if downvote %>"></a>
    <% else %>
        <%= link_to 'Sign up to vote now!', signup_path %>
    <% end %>
  </small>
</h2>

<div class="build-info">
  <h4><%= pluralize(@build_info.rating, 'point') %>
    <small> <%= @build_info.rating > 0 ? (@build_info.upvotes/(@build_info.upvotes+@build_info.downvotes)*100) : 0 %>
      %
    </small>
  </h4>
  <table class="table">
    <tr>
      <td><strong>Matchup:</strong></td>
      <td>
        <img title="<%= @build_info.race.race_name %>" src="<%= asset_path @build_info.race.race_image %>"/>
        v
        <img title="<%= @build_info.versus_race.race_name %>" src="<%= asset_path @build_info.versus_race.race_image %>"/>
      </td>
    </tr>
    <tr>
      <td><strong>Build Type:</strong></td>
      <td>
        <%= @build_info.build_type.type_name %>
      </td>
    </tr>
    <tr>
      <td><strong>Difficulty:</strong></td>
      <td>
        <%= @build_info.difficulty.difficulty_name %>
      </td>
    </tr>
    <tr>
      <td><strong>Key Units:</strong></td>
      <td>
        <% @build_info.units.each do |unit| %>
            <img src="<%= asset_path unit.unit_image %>"/><%= unit.unit_name %>
        <% end %>
      </td>
    </tr>
    <tr>
      <td><strong>Expansion:</strong></td>
      <td>
        <img src="<%= asset_path @build_info.expansion.expansion_image %>"/>
        <span><%= @build_info.expansion.expansion_name %></span>
      </td>
    </tr>
    <tr>
      <td><strong>Created:</strong></td>
      <td>
        <%= @build_info.created.strftime('%d/%m/%Y %I:%M%p') %>
      </td>
    </tr>
    <tr>
      <td><strong>Created by:</strong></td>
      <td>
        <%= link_to @build_info.user.user_name, user_path(@build_info.user) %>
      </td>
    </tr>
  </table>
  <h3>Build Steps</h3>
  <table>
    <% @build_info.build_steps.each do |step| %>
        <tr>
          <td><%= step.step %></td>
        </tr>
    <% end %>
  </table>
  <h3>Build Guide</h3>

  <p class="guide">
    <% if !@build_info.build_guide.nil? %>
        <%= @build_info.build_guide.guide.html_safe %>
    <% end %>
  </p>
</div>