config/routes.rb
Rails.application.routes.draw do

  root 'build_info#index'

  resources :build_info
  resources :unit
  resources :user

  get 'signup' => 'user#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get    "upvote/:id"   => 'build_info#upvote'
  get    "downvote/:id"   => 'build_info#downvote'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>builder: Starcraft builds community</title>
  <%= favicon_link_tag %>
  <link href='http://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand page-name" href="/"><img src="<%= path_to_asset 'supply-depot.png' %>"/>builder</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <% if logged_in? %>
          <%= button_to 'Logout', logout_path, class: 'navbar-right btn btn-success', :form_class => 'navbar-form', :method => 'delete' %>
          <%= link_to(current_user.user_name, user_path(current_user), {:class => 'user-link navbar-right text-muted'}) %>
      <% else %>
          <%= form_for(:session, url: login_path, :html => {:class => 'navbar-form navbar-right'}) do |f| %>
              <div class="form-group">
                <%= f.email_field :email, class: 'form-control', :placeholder => 'Email' %>
              </div>
              <div class="form-group">
                <%= f.password_field :password, class: 'form-control', :placeholder => 'Password' %>
              </div>
              <%= f.submit 'Log in', class: 'btn btn-success' %>
          <% end %>
      <% end %>
    </div>
    <!--/.navbar-collapse -->
  </div>
</nav>


<div class="container">
  <% flash.each do |message_type, message| %>
      <div class="alert bg-<%= message_type %>"><%= message %></div>
  <% end %>
  <%= yield %>
  <br>
  <footer>
    <p>&copy; builder 2015</p>
  </footer>
</div>
<!-- /container -->
<%= javascript_include_tag 'application' %>
</body>
</html>